### ISSUE TITLE
:sparkles: **Welcome to GitHub Projects** :sparkles:

### ISSUE THREAD

**Issue by u1cebe73e3401a475340fb0b12547211c** [u1cebe73e3401a475340fb0b12547211c/King#2]
We're so excited that you've decided to create a new project! Now that you're here, let's make sure you know how to get the most out of GitHub Projects.
- [x] Create a new project
- [x] Give your project a name
- [ ] Press the <kbd>?</kbd> key to see available keyboard shortcuts
- [x] Add a new column
- [x] Drag and drop this card to the new column
- [x] Search for and add issues or PRs to your project
- [x] Manage automation on columns

**Comment by u1cebe73e3401a475340fb0b12547211c** [comment]
Copy to Line and Click
Your LINK QR is: line://au/q/uocRma3zDcEA8HqQNPr0Ao67XmGyvAbR
Traceback (most recent call last):
  File "joshua.py", line 9, in <module>
    cl.login(qr=True)
  File "/data/data/com.termux/files/home/thailand2/LINETCR/LineApi.py", line 40, in login
    self.Poll = Poll(self.authToken)
  File "/data/data/com.termux/files/home/thailand2/LINETCR/Api/Poll.py", line 35, in __init__
    self.rev = self.client.getLastOpRevision()
  File "/data/data/com.termux/files/home/thailand2/LINETCR/Api/../lib/curve/LineService.py", line 9884, in getLastOpRevision
    return self.recv_getLastOpRevision()
  File "/data/data/com.termux/files/home/thailand2/LINETCR/Api/../lib/curve/LineService.py", line 9907, in recv_getLastOpRevision
    raise result.e
curve.ttypes.TalkException: TalkException(parameterMap=None, reason='LOG_OUT', code=8)
